global:
  environment: local

persistence:
  storageClassName: local-path
  postgres:
    size: 1Gi
  minio:
    size: 2Gi

database:
  user: postgres
  password: postgrespassword
  name: postgres
  port: 5432

ai:
  model: gemini-3.5-flash-lite
  apiKey: ""

services:
  client:
    image: gratitudeapp-client:local
    replicas: 1
    containerPort: 80
  apiGateway:
    image: gratitudeapp-api-gateway:local
    replicas: 1
    port: 5000
  entries:
    image: gratitudeapp-entries:local
    replicas: 1
    port: 50051
  moodsService:
    image: gratitudeapp-moods-service:local
    replicas: 1
    port: 50052
  moodsApi:
    image: prashantdey/merndemoapp:moodsapiv1.0
    replicas: 1
    port: 5002
  statsService:
    image: gratitudeapp-stats-service:local
    replicas: 1
    port: 50053
  statsApi:
    image: prashantdey/merndemoapp:statsapiv1.0
    replicas: 1
    port: 5003
  filesService:
    image: gratitudeapp-files-service:local
    replicas: 1
    port: 9002
  postgres:
    image: postgres:15-alpine
  minio:
    image: cgr.dev/chainguard/minio:latest
    rootUser: minioadmin
    rootPassword: minioadmin
