apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
stringData:
  PGUSER: "postgres"
  PGHOST: "postgres-cluster-ip-service"
  PGDATABASE: "postgres"
  PGPASSWORD: "postgrespassword"
  PGPORT: "5432"
