apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
stringData:
  PGUSER: {{ .Values.database.user | quote }}
  PGHOST: "postgres-cluster-ip-service"
  PGDATABASE: {{ .Values.database.name | quote }}
  PGPASSWORD: {{ .Values.database.password | quote }}
  PGPORT: {{ .Values.database.port | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: openai-api-secret
type: Opaque
stringData:
  OPENAI_API_KEY: {{ .Values.ai.apiKey | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gratitude-config
data:
  PORT: "{{ .Values.services.apiGateway.port }}"
  ENTRIES_SERVICE_ADDR: "entries-cluster-ip-service:{{ .Values.services.entries.port }}"
  MOODS_SERVICE_ADDR: "moods-service-cluster-ip-service:{{ .Values.services.moodsService.port }}"
  FILES_SERVICE_ADDR: "files-service:{{ .Values.services.filesService.port }}"
  POSTGRES_HOST: "postgres-cluster-ip-service"
  POSTGRES_PORT: "{{ .Values.database.port }}"
  POSTGRES_DB: {{ .Values.database.name | quote }}
  MINIO_ENDPOINT: "http://minio-service:9000"
  MINIO_BUCKET: "gratitude-uploads"
  OPENAI_MODEL: {{ .Values.ai.model | quote }}
